weblate:
  build: weblate
  links:
    - database
    - cache
  ports:
    - "8000:8000"
  volumes:
    - ./weblate:/app/etc:ro
  env_file:
    - ./weblate/environment
database:
  # You can change used database here:
  image: postgres:9.4
  volumes:
    - ./weblate/mysql-charset.conf:/etc/mysql/conf.d/charset.cnf
  env_file:
    - ./weblate/environment
cache:
    image: memcached:1.4
